### PR TITLE
changed proptype from error to warn

### LINKED ISSUE #3: Change PropTypes restriction
Change `react/prop-types` from `error` to `warn`:
```
"react/prop-types": ["warn", {
  "ignore": [],
  "customValidators": [],
  "skipUndeclared": false
}]
```

### PR DESCRIPTION
**Pull request by VitorVRS**
Closes #3

### CODE REVIEW

**Review by talesbaz — APPROVED** [review]

**Comment by talesbaz** [comment]
@VitorVRS after this has been approved you, my friend, is responsible for pack and publish the package. ;*

**Review by nathpaiva — APPROVED** [review]
🚀

**Review by costamauricio — APPROVED** [review]

**Review by joaopluigi — APPROVED** [review]

**Review by vitor-tadashi — APPROVED** [review]

**Review by pablomdo — APPROVED** [review]

**Comment by talesbaz** [comment]
@VitorVRS you can go ahead comrade!

**Comment by VitorVRS** [comment]
Package published with version 2.3.0

**Pull request merged**
